const express = require("express");
const authrouter = express.Router();
const createfullname = require("../middlewares/createfullname");
const createuser = require("../controllers/registeruser");
const hashpass = require("../middlewares/crypt");
const decrypte = require("../../auth/controllers/decrypt");
const login = require("../controllers/loginuser");
authrouter.get("/decrypt", decrypte);
authrouter.post("/login", login);
authrouter.post("/sign_up", createfullname, hashpass, createuser);
module.exports = authrouter;
